name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - pandas
    - ipywidgets
    - sklearn
    - tensorflow
    - bqplot
    - datapane
    - pmdarima
    - pyFTS
    - matplotlib
    - dill
    - pystan
    - prophet
